Gamelogic
TINF21CS1/TicTacToeKojote pull request #2
Opened 2024-02-15 15:42 UTC by JM-Lemmi

Closes TTTK-7 TTTK-8 TTTK-9

2024-02-15 17:46 UTC, Petzys commented
Most of these classes and methods can be easily tested. Please add tests to verify the functionality.

2024-02-15 17:48 UTC, Petzys commented
Additionally, we need more documentation in the code. 
At least add doc strings to the classes like [here](https://peps.python.org/pep-0257/).

2024-02-15 18:24 UTC, Petzys requested changes

2024-02-15 18:24 UTC, Petzys commented on Game/rulebase.py
> +        return 0
These methods are not capable of handling playfields larger than 3*3. 
Additionally, this just looks straight up ugly. Please try to use iteration over the playfield dimensions etc.

2024-02-15 18:24 UTC, Petzys commented on Game/rulebase.py
> +        return "" #TODO
I just realized that it makes no sense at all to have a "prev" parameter for explain() since TicTacToe does not work that way. I already changed the class diagram. Please remove the "prev" parameter. We only need "new" and the state.

Additionally, Implement these functions. 
Explain can be very generic (e.g. "This field is already taken. Take an empty one". "It is not your turn").
Remember to also implement the OK case: Explain can be called on legal moves too.

2024-02-15 18:24 UTC, Petzys commented on Game/game.py
> +        self._id: int = 1 #TODO count up
Using a random number with a high entropy should be enough in this case. (Or do something else)

2024-02-15 18:24 UTC, Petzys commented on Game/rulebase.py
> +        return self._check_win_horizontal(state) or self._check_win_vertical(state) or self._check_win_diagonal(state)
This method does not implement a draw when all field are filled but none of the players won.

I recommend to change the GameStates winner and finish attribute here. Afterwards, Game checks for the attributes of game states and evaluates whether it is draw or who is the winner

2024-02-15 18:24 UTC, Petzys commented on Game/game.py
> +            return None
Also think about the draw possibility here

2024-02-15 18:24 UTC, Petzys commented on Game/rulebase.py
> +            raise ValueError("Invalid playfield value")
You should also check if the player who wants to move is the current player.

2024-02-15 18:24 UTC, Petzys commented on Game/game.py
> +            raise ValueError("Illegal move")
In this line you should Raise the output of RuleBase.explain(). 

Additionally, I would recommend using a custom Error Class, that you can raise. This allows for easier storage of error related values e.g. the position which is not allowed. But this is optional.

2024-02-18 11:00 UTC, JM-Lemmi commented on Game/rulebase.py
> +        return 0
isnt that the point of this class? Any other ruleset should be an extension of this class with overwritten functions.

2024-02-18 11:25 UTC, JM-Lemmi commented on Game/rulebase.py
> +        return 0
c2613fa

2024-02-18 11:45 UTC, JM-Lemmi commented on Game/rulebase.py
> +        return self._check_win_horizontal(state) or self._check_win_vertical(state) or self._check_win_diagonal(state)
43655aa

2024-02-18 11:45 UTC, JM-Lemmi commented on Game/game.py
> +            return None
43655aa

2024-02-18 11:47 UTC, JM-Lemmi commented on Game/rulebase.py
> +            raise ValueError("Invalid playfield value")
Mit den gegebenen werten kann diese Funktion das gar nicht checken.

2024-02-18 11:48 UTC, JM-Lemmi commented on Game/rulebase.py
> +            raise ValueError("Invalid playfield value")
Wird außerdem von is_state_valid abgedeckt falls man das danach checken möchte. ich wäre einfach dafür, dass die usptream funktionen tracken, wer grade dran ist.

2024-02-18 11:48 UTC, JM-Lemmi commented on Game/game.py
> +            raise ValueError("Illegal move")
I hate the explain function anyway. Ist das eine muss-anforderung? sonst würde ich das streichen.

2024-02-18 12:17 UTC, JM-Lemmi commented
Ich würde auch gerne den `GameState.current_player()` entfernen, das ist einfach nicht nötig.

2024-02-18 16:44 UTC, Petzys commented on Game/game.py
> +            raise ValueError("Illegal move")
Actually yes. This is necessary.

2024-02-18 17:04 UTC, Petzys requested changes
Well done and thanks! Only a few things still left to do but this is very nice!

2024-02-18 17:04 UTC, Petzys commented on Game/rulebase.py
> +        return ""  # TODO
Please implement

2024-02-18 17:04 UTC, Petzys commented on Game/game.py
> +            raise ValueError("Illegal move")
TODO

2024-02-18 17:04 UTC, Petzys commented on Game/game.py
> +        self._id: int = 1 #TODO count up
TODO

2024-02-18 17:04 UTC, Petzys commented on Game/test_gamestate.py
For next time: Please use python unittests. Do not implement tests yourself using basic asserts. But its ok for now.

2024-02-18 18:16 UTC, JM-Lemmi commented on Game/rulebase.py
> +        return ""  # TODO
Wie gesagt würde ich das gerne eigentlich streichen, außer es gibt dazu spezifische Anforderungen

2024-02-18 18:20 UTC, JM-Lemmi commented on Game/rulebase.py
> +        return ""  # TODO
Ah hab den Kommentar gefunden.

2024-02-23 11:10 UTC, Petzys approved these changes

2024-02-23 11:10 UTC, merged