Statistics
TINF21CS1/TicTacToeKojote pull request #6
Opened 2024-03-07 10:10 UTC by bananabr3d

Manages statistics.db. Can add, update and delete statistics. Identification of statistics via player uuid.

2024-03-12 13:16 UTC, bananabr3d commented
tests have been added and fixed :D

2024-03-12 14:16 UTC, Petzys requested changes

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +            print("found")
use logging, not print

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +            print("not found")
use logging, not print

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +                print("json error: Make sure profiles.json is formatted correctly")
use logging, not print

2024-03-12 14:16 UTC, Petzys commented on json_schema/profiles.json
Falls das die Datei sein soll, wo der Nutzer sein Profil persistiert, ist das nicht die richtige File Location. Eher unter /Client

2024-03-12 14:16 UTC, Petzys commented on json_schema/profiles.json
Das ist ja gar kein JSON Schema

2024-03-12 14:16 UTC, Petzys commented on Server/test_statistics.py
> +test = TestStatistics()
Bitte mit `__name__ = __main__`. Nicht so.

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +                print("json error: Make sure profiles.json is formatted correctly")
use logging, not print

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +                print("json error: Make sure profiles.json is formatted correctly")
use logging, not print

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +                print("json error: Make sure profiles.json is formatted correctly")
Sollte diese Funktion nicht tatsächlich einen Error werfen, wenn das JSON halt falsch ist? Also bringt ja nichts, wenn das hier geloggt wird, wenn hier ein Fehler vorliegt.

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
> +#print(profile.get_profiles())
Remove

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +                WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +                WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +                WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +                WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +                WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +            WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Server/statistics.py
> +            WHERE uuid = '{uuid}'
This is a SQL Injection. Maybe use prepared Statements.

2024-03-12 14:16 UTC, Petzys commented on Client/profile_save.py
In diesem ganzen Modul solltest du immer mit den echten Profiles aus Server/Profiles.py arbeiten. Du solltest Profile Objects und keine Dictionaries zurückgeben. Das macht es leichter.

2024-03-14 08:58 UTC, Petzys requested changes

2024-03-14 08:58 UTC, Petzys commented on Server/statistics.py
> +    def update_statistics(self, uuid: str, type: str, moves: int) -> None:
update_statistics should call add_profile if the profile does not exist. This makes this a lot easier for the server

2024-03-14 09:05 UTC, JM-Lemmi requested changes

2024-03-14 09:05 UTC, JM-Lemmi commented on Client/profile_save.py
why is this here?

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/Data/statistics.db
gitignore!

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +    """
?

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +        loses_second : int, draws : int, moves : int, emojis : int)
das ist ja wohl ein dict

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +    def update_statistics(self, uuid: str, type: str, moves: int) -> None:
this call always needs a get call beforehand. please add an "increment_moves" function or similar.

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +        self._update_emojis(uuid, emoji.emoji_count(message))
this doesnt increment but overwrite the emoji count

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +
missing function to increment winrate

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +    def update_statistics(self, uuid: str, type: str, moves: int) -> None:
No it doesnt, it does actually increment, but the docstring is wrong

2024-03-14 09:05 UTC, JM-Lemmi commented on Server/statistics.py
> +        :param uuid: uuid of the profile that is added
missing profile name

2024-03-14 09:08 UTC, JM-Lemmi commented on Server/statistics.py
> +    def update_statistics(self, uuid: str, type: str, moves: int) -> None:
+1

2024-03-14 09:13 UTC, JM-Lemmi commented
functions I need as the server:

```
increment_moves(player, count = 1)
increment_emoji(player, message)
increment_wins_fromstate(gamestate)
```

2024-03-14 21:53 UTC, JM-Lemmi approved these changes

2024-03-15 10:48 UTC, Petzys approved these changes
Nice work!

2024-03-15 11:16 UTC, Petzys commented
After testing I fixed some minor bugs.

2024-03-15 11:17 UTC, merged