feat: profile_save.py and profiles.json added, saves profiles and ret…
TINF21CS1/TicTacToeKojote pull request #7
Opened 2024-03-07 10:16 UTC by bananabr3d

Manages profiles.json. Can Add, update and remove profiles

2024-03-07 10:23 UTC, JM-Lemmi requested changes

2024-03-07 10:23 UTC, JM-Lemmi commented on Client/profile_save.py
> +                            break
```suggestion
    def set_profile(self, profile_uuid , profile_name, profile_color):
        """
        This method sets the profile name and/or color by the uuid
        :param profile_uuid:
        :param profile_name: *optional*
        :param profile_color: *optional*
        """
        if profile_name == None || profile_color == None:
            raise ValueError("name or color cannot be none")
        
        if self.check_file():
            try:
                with open(path, 'r+') as file:
                    data = json.load(file)
                    for profile in data:
                        if profile["profile_uuid"] == profile_uuid:
                            profile["profile_name"] = profile_name
                            profile["profile_color"] = profile_color
                            break
```

2024-03-07 10:23 UTC, JM-Lemmi commented on Client/profile_save.py
> +#print(profile.get_profiles())
?

2024-03-07 10:23 UTC, JM-Lemmi commented on json_schema/profiles.json
> +[]
bitte füllen

2024-03-12 13:12 UTC, bananabr3d commented on Client/profile_save.py
> +#print(profile.get_profiles())
Ist im aktuellen durch richtige Tests

2024-03-12 13:12 UTC, bananabr3d commented on json_schema/profiles.json
> +[]
Womit? D:

2024-03-12 16:29 UTC, JM-Lemmi commented on json_schema/profiles.json
> +[]
na mit dem schema

2024-03-13 08:06 UTC, Petzys commented on json_schema/profiles.json
> +[]
Das soll gar kein Schema sein @JM-Lemmi . Die Datei ist einfach nur am falschen Ort. Siehe mein Review in #6 .

2024-03-14 08:43 UTC, HOOK-Hawkins requested changes

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +        if self.check_file():
```suggestion
        if exists(self.path):
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +        if self.check_file():
```suggestion
        if exists(self.path):
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
### 
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +            return None
```suggestion
            return []
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +        if self.check_file():
```suggestion
```

2024-03-14 08:43 UTC, HOOK-Hawkins commented on Client/profile_save.py
> +        return None
```suggestion
```

2024-03-14 09:14 UTC, HOOK-Hawkins approved these changes

2024-03-14 09:14 UTC, merged